"""Point Formula/continuum.rb at the latest party-continuum release on PyPI.

Prints the version when the formula changed, nothing when it is current.
"""

import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

FORMULA = Path(__file__).resolve().parents[2] / "Formula" / "continuum.rb"
TEMPLATE = """\
# Generated by .github/scripts/update_formula.py from PyPI party-continuum; edits are overwritten.
class Continuum < Formula
  desc "Static change impact of a checkout: dependents, reach and tests to run"
  homepage "https://pypi.org/project/party-continuum/"
  url "@URL@"
  sha256 "@SHA256@"

  depends_on "python@3.13"

  # Standard library only: the package directory is installed as-is, no virtualenv needed.
  def install
    libexec.install "party_continuum"
    python = Formula["python@3.13"].opt_bin/"python3.13"
    (bin/"continuum").write <<~SH
      #!/bin/sh
      exec "#{python}" -P -c 'import sys; sys.path.insert(0, sys.argv.pop(1)); from party_continuum.cli import main; sys.exit(main())' "#{libexec}" "$@"
    SH
  end

  test do
    assert_match "usage: continuum", shell_output("#{bin}/continuum --help")
  end
end
"""


def main():
    try:
        with urllib.request.urlopen("https://pypi.org/pypi/party-continuum/json", timeout=30) as r:
            release = json.load(r)
    except urllib.error.HTTPError as error:
        if error.code == 404:
            print("party-continuum is not on PyPI yet", file=sys.stderr)
            return 0
        raise
    version = release["info"]["version"]
    sdist = [u for u in release["urls"] if u["packagetype"] == "sdist"]
    if len(sdist) != 1:
        raise SystemExit(f"party-continuum {version}: expected one sdist, found {len(sdist)}")
    text = TEMPLATE.replace("@URL@", sdist[0]["url"]).replace(
        "@SHA256@", sdist[0]["digests"]["sha256"]
    )
    if FORMULA.exists() and FORMULA.read_text() == text:
        return 0
    FORMULA.parent.mkdir(parents=True, exist_ok=True)
    FORMULA.write_text(text)
    print(version)
    return 0


if __name__ == "__main__":
    sys.exit(main())
