# Generated by .github/scripts/update_formula.py from PyPI party-continuum; edits are overwritten.
class Continuum < Formula
  desc "Static change impact of a checkout: dependents, reach and tests to run"
  homepage "https://pypi.org/project/party-continuum/"
  url "https://files.pythonhosted.org/packages/ff/f0/ba006b56761e81ccd70894157951be0ad8c04f427d91cb71737965667545/party_continuum-0.4.0.tar.gz"
  sha256 "21b2bf3dadfff0f50442fdc5b1936a90c6610c6097a0ce25e8655adbdbfac327"

  depends_on "python@3.13"

  # Standard library only: the package directory is installed as-is, no virtualenv needed.
  def install
    libexec.install "party_continuum"
    python = Formula["python@3.13"].opt_bin/"python3.13"
    (bin/"continuum").write <<~SH
      #!/bin/sh
      exec "#{python}" -P -c 'import sys; sys.path.insert(0, sys.argv.pop(1)); from party_continuum.cli import main; sys.exit(main())' "#{libexec}" "$@"
    SH
  end

  test do
    assert_match "usage: continuum", shell_output("#{bin}/continuum --help")
  end
end
