# Generated by .github/scripts/update_formula.py from PyPI party-continuum; edits are overwritten.
class Continuum < Formula
  desc "Static change impact of a checkout: dependents, reach and tests to run"
  homepage "https://pypi.org/project/party-continuum/"
  url "https://files.pythonhosted.org/packages/e2/f3/50feaac11665e008c833e3136f29b61428abb8afbfe2a3a340dbc8c3a6df/party_continuum-0.2.1.tar.gz"
  sha256 "9e450f55db9a7018dd424d4fae3830314441dbd14efc998b6a0682efeb782a19"

  depends_on "python@3.13"

  # Standard library only: the package directory is installed as-is, no virtualenv needed.
  def install
    libexec.install "party_continuum"
    python = Formula["python@3.13"].opt_bin/"python3.13"
    (bin/"continuum").write <<~SH
      #!/bin/sh
      exec "#{python}" -P -c 'import sys; sys.path.insert(0, sys.argv.pop(1)); from party_continuum.cli import main; sys.exit(main())' "#{libexec}" "$@"
    SH
  end

  test do
    assert_match "usage: continuum", shell_output("#{bin}/continuum --help")
  end
end
